[package]
name = "merkle-sim"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10"
clap = { version = "4.3", features = ["derive"] }
hex = "0.4"
proof-verifier = { path = "../proof-verifier" }